[project]
name = "enum2string"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clang==14",
]

[dependency-groups]
dev = [
    "objprint>=0.3.0",
    "ptpython>=3.0.30",
    "pudb>=2025.1",
]
